### ISSUE TITLE
[BUG] Cypress is entering incorrect data into the search input

### ISSUE THREAD

**Issue by justynafenik1** [polubis/Dream-stack-for-React-dev#354]
In pull request [adding article process test](https://github.com/polubis/Dream-stack-for-React-dev/pull/342) there is a problem with typing data to search input on website https://dream-stack-for-react-dev-git-feature-finish-art-9e117f-polubis.vercel.app/en/articles. When automation test enter text 'article 4' on input,cypress randomly enters  every x-nd letter:

![image](https://github.com/polubis/Dream-stack-for-React-dev/assets/145045383/6e82ef46-74ae-47bc-b5f8-cbb03ff53c10)
![image](https://github.com/polubis/Dream-stack-for-React-dev/assets/145045383/96460c38-ff23-46a4-9b46-b3af9b0f9cfc)

comment: in manual test it works corretly

**Comment by polubis** [comment]
@justynafenik1  you may test it on following branch: 
https://github.com/polubis/Dream-stack-for-React-dev/pull/355

To load the changes on your branch with automated tests, just do git pull patch/Fix-current-defects when you'll be on your branch.

**Comment by justynafenik1** [comment]
The bug has been fixed
